name: Run all checks
on:
  pull_request: null
  push:
    branches: main
jobs:
  formatter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Install Nix
        uses: cachix/install-nix-action@456688f15bc354bef6d396e4a35f4f89d40bf2b7 # v31.8.2
        with:
          extra_nix_config: |
            keep-outputs = true
            keep-env-derivations = true
      - name: Cache action
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
        with:
          diagnostic-endpoint: ""
          use-flakehub: false
      - name: Run Nix flake checks
        run: nix flake check
